services:
  db:
    image: postgres:15.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: always
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
      interval: 30s
      timeout: 10s
      retries: 15
    ports:
    - "${POSTGRES_PORT}:5432"

  backend:
    build: ../skymarket
    container_name: 'backend_skymarket'
    ports:
      - '8001:8000'
    tty: true
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    env_file:
      - ../.env
    volumes:
      - ../skymarket:/skymarket
      - ../skymarket/django_static:/usr/share/nginx/html/django_static/
      - ../skymarket/django_media:/usr/share/nginx/html/django_media/
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ./frontend_react/.
    volumes:
      - frontend:/app/build

  nginx:
    image: nginx:1.19.3
    ports:
      - "8000:8000"
      - "3000:3000"
    volumes:
      - ./skymarket/django_static/:/usr/share/nginx/html/django_static/
      - ./skymarket/django_media/:/usr/share/nginx/html/django_media/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - frontend:/usr/share/nginx/html/
    restart: always
    depends_on:
      - frontend

volumes:
  postgres_data:  
  frontend: